# Generated by Django 3.0.8 on 2021-05-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Media')),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'db_table': 'table_amenity',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('slug', models.SlugField(default='', max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'table_category',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookerville_id', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(default='', max_length=64, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(default='')),
                ('neighbourhood', models.TextField(default='')),
                ('transit', models.TextField(default='')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('price', models.IntegerField()),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('min_month_price', models.IntegerField(blank=True, null=True)),
                ('sleeps', models.IntegerField(default=1)),
                ('min_sleeps', models.IntegerField(blank=True, default=1, null=True)),
                ('bedroom_count', models.IntegerField(default=1)),
                ('bathroom_count', models.FloatField(default=1)),
                ('shared_bathroom', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=True)),
                ('rental_parking', models.BooleanField(default=True)),
                ('pets_considered', models.BooleanField(default=True)),
                ('cleaning_fee', models.IntegerField(blank=True, null=True)),
                ('transactionfee_rate', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('refundable_amount', models.IntegerField(blank=True, null=True)),
                ('tour360', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='property_amenities', to='accommodation.Amenity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='accommodation.Category')),
                ('featured_img', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured', to='media.Media')),
                ('gallery_imgs', models.ManyToManyField(blank=True, related_name='property_gallery', to='media.Media')),
                ('similar_properties', models.ManyToManyField(blank=True, related_name='_property_similar_properties_+', to='accommodation.Property')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'table_property',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_type', models.CharField(blank=True, choices=[('T', 'Twin Bed'), ('S', 'Sofa Bed'), ('Q', 'Queen Bed'), ('K', 'King Bed'), ('C', 'Chair Bed'), ('M', 'Murphy Bed'), ('F', 'Full Bed'), ('P', 'Single Chair Sleeper Bed')], default='T', max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_rooms', to='accommodation.Property')),
            ],
            options={
                'db_table': 'table_room',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='price for specific period')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_items', to='accommodation.Property')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
                'db_table': 'table_price',
            },
        ),
    ]
