# Generated by Django 3.2.3 on 2022-01-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='price for specific month')),
                ('date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlypricing_items', to='accommodation.property')),
            ],
            options={
                'verbose_name': 'monthlyprice',
                'verbose_name_plural': 'monthlyprices',
                'db_table': 'table_monthlyprice',
            },
        ),
    ]
