# Generated by Django 3.2.3 on 2022-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='zip_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
