# Generated by Django 3.2.3 on 2022-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
