# Generated by Django 3.2.3 on 2021-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('meta_tags', models.JSONField()),
                ('og_tags', models.JSONField()),
                ('twitter_tags', models.JSONField()),
            ],
            options={
                'db_table': 'table_meta',
            },
        ),
    ]
