# Generated by Django 3.2.3 on 2021-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='meta_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='og_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='twitter_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
