name: Backend CI/CD

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to Starsofboston Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/stars_django_api
            sudo git fetch origin
            sudo git reset --hard origin/master
            source venv/bin/activate
            pip3 install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
