name: Backend CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  repository_dispatch:
    types: [production-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - name: SSH and deploy to Starsofboston Backend
        uses: appleboy/ssh-action@master
        timeout-minutes: 30
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command_timeout: 60m
          script: |
            cd /var/starsofboston/stars_django_api
            sudo git pull origin master
            source venv/bin/activate
            pip3 install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            sudo systemctl restart gunicorn.socket
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx


